version: 0.1.1
name: cryaml
description: crYAML — YAML on steroids

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  petitparser: ^2.3.0

dev_dependencies:
  test: 1.6.4
  mockito: 4.1.0
  test_coverage: ^0.3.0

